---
title: "Homework 6"
author: "Dania Jafar"
date: "11/15/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
birthweight = read.csv("./birthweight.csv") %>% 
  mutate(babysex = as.factor(babysex),
         frace = as.factor(frace),
         mrace = as.factor(mrace),
         malform = as.factor(malform))
```

# Problem 1
```{r}
#In this model, I have decided to use mother's smoking status, race, age at delivery, and baby's gestational age in weeks as the predictors for my model. I have chosen these factors as they seem to be some of the most important predictors for a child's weight at birth. 

birthweight2 = birthweight %>% #create a new dataset for the model I want to generate
  select(bwt, smoken, mrace, gaweeks, momage)

fit = lm(bwt ~ smoken + mrace + gaweeks + momage, data = birthweight2)

#obtaining a quick summary of the model 
fit %>% 
  broom::glance()

fit %>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  knitr::kable(digits = 3)

library(modelr)

#create a variable that predicts birthweight

birthweight2 = modelr::add_predictions(birthweight2, fit)

#plots of birthweight by residuals 
plot1 = 
birthweight2 %>%   #scatter plot
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = pred, y = resid)) + geom_point() +
  labs(x = "predicted birthweight", y = "residual")

plot1
```


```{r}
#Comparing my model to two others

linear_mod2 = lm(bwt ~ blength + gaweeks, data = birthweight)
linear_mod3 = lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = birthweight)

 #plotting a model to get a sense for their goodness of fit.

cv_df = 
  crossv_mc(birthweight, 100)

cv_df =
  cv_df %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_df = 
  cv_df %>% 
  mutate(fit  = map(train, ~lm(bwt ~ smoken + mrace + gaweeks + momage, data = .x)),
         linear_mod2  = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
         linear_mod3  = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead*blength + bhead*babysex + blength*babysex + bhead*blength*babysex, data = .x))) %>% 
  mutate(rmse_fit = map2_dbl(fit, test, ~rmse(model = .x, data = .y)),
         rmse_lm2 = map2_dbl(linear_mod2, test, ~rmse(model = .x, data = .y)),
         rmse_lm3 = map2_dbl(linear_mod3, test, ~rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

#I can see that linear model three (lm3) is the best one because it produces the lowest root mean square error. 

```
# Problem 2
```{r Load data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```
```{r}

#Create a linear model
lm(tmax ~ tmin, data = weather_df) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)

#Create the boot sample
x = weather_df

boot_sample = function(x) {
  sample_frac(x, replace = TRUE)
}

#Check to see if this is working.

boot_sample(x) %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")

#Drawing 5000 bootstrap samples

boot_straps_data = 
  list(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(x))
  )

#Getting the r-hat-squared
weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data =.x)),
    results = map(models, broom::glance)) %>% 
    select(-strap, -models) %>% 
    unnest(results) %>% 
    janitor::clean_names() %>% 
  ggplot(aes(x = r_squared)) + #create a density plot of r-squared
  geom_density()

#Getting the log(β̂ 0∗β̂ 1)
data1 = 
weather_df %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data =.x)),
    results = map(models, broom::tidy)) %>% 
    select(-strap, -models) %>% 
    unnest(results) %>% 
   janitor::clean_names() %>% 
  pivot_wider(
    names_from = "term",
    values_from = "estimate"
  )  %>% 
  rename(intercept= '(Intercept)') %>% 
  mutate(log_calc = log(intercept*tmin)) %>% 
  pull(log_calc, quantile(., probs = c(0.025, 0.975, 0.95)))


```



